<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-05T01:58:45 IST" name="Suite" finished-at="2021-10-05T01:59:40 IST" duration-ms="55168">
    <groups>
    </groups>
    <test started-at="2021-10-05T01:58:45 IST" name="Test" finished-at="2021-10-05T01:59:40 IST" duration-ms="55168">
      <class name="oct2_extents.LoginTestCases">
        <test-method is-config="true" signature="testbefore()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:58:45 IST" name="testbefore" finished-at="2021-10-05T01:58:45 IST" duration-ms="530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testbefore -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:58:45 IST" name="beforeMethod" finished-at="2021-10-05T01:58:50 IST" duration-ms="4356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="NavigateToBrowser()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:58:50 IST" name="NavigateToBrowser" finished-at="2021-10-05T01:59:10 IST" duration-ms="20623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToBrowser -->
        <test-method signature="TestCase001()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:59:10 IST" name="TestCase001" finished-at="2021-10-05T01:59:20 IST" duration-ms="9235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase001 -->
        <test-method is-config="true" signature="NavigateToBrowser()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:59:20 IST" name="NavigateToBrowser" finished-at="2021-10-05T01:59:34 IST" duration-ms="14381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToBrowser -->
        <test-method signature="TestCase002()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:59:34 IST" name="TestCase002" finished-at="2021-10-05T01:59:39 IST" duration-ms="4682" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at oct2_extents.LoginTestCases.TestCase002(LoginTestCases.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase002 -->
        <test-method signature="TestCase003()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:59:39 IST" name="TestCase003" finished-at="2021-10-05T01:59:39 IST" depends-on-methods="oct2_extents.LoginTestCases.TestCase002" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTestCases.TestCase003()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTestCases.TestCase003()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase003 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:59:39 IST" name="afterMethod" finished-at="2021-10-05T01:59:40 IST" duration-ms="961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="testafter()[pri:0, instance:oct2_extents.LoginTestCases@1dd0e7c4]" started-at="2021-10-05T01:59:40 IST" name="testafter" finished-at="2021-10-05T01:59:40 IST" duration-ms="248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testafter -->
      </class> <!-- oct2_extents.LoginTestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
